logging:
  level:
    com.dealer: INFO
    root: WARN
  pattern:
    console: >-
      {"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","logger":"%logger","thread":"%thread","message":"%message","exception":"%exception"}%n

management:
  tracing:
    sampling:
      probability: 0.1

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false

app:
  cache:
    enabled: ${CACHE_ENABLED:true}
  firebase:
    enabled: ${FIREBASE_ENABLED:true}
    messaging-token-path: ${FIREBASE_TOKEN_PATH:/etc/fca.json}
